"""
LOG — Immutable action history.

Every point mutation (infraction, bonus, collective malus, cancellation)
creates a log entry. Logs are NEVER deleted — only marked `annule=True`
by the Kill Switch.

Critical field: `source_type`
  - DIRECT:    logged by an Ancien/P3 — can trigger collective malus
  - COLLECTIF: auto-generated by collective malus — NEVER cascades
  - CANCEL:    auto-generated by Kill Switch
"""
from datetime import datetime

from peewee import (
    AutoField,
    CharField,
    IntegerField,
    ForeignKeyField,
    DateTimeField,
    TextField,
    BooleanField,
)

from app.database import BaseModel
from app.models.personne import Personne


class Log(BaseModel):
    id = AutoField()

    # ── Who ───────────────────────────────────────────────
    # conscrit who received the infraction/bonus
    conscrit = ForeignKeyField(Personne, backref="logs", on_delete="CASCADE")
    # ancien/P3 who logged it (null = system auto-generated)
    ancien = ForeignKeyField(
        Personne, backref="logs_created", null=True, default=None,
        on_delete="SET NULL",
    )

    # ── What ──────────────────────────────────────────────
    code_infraction = CharField(max_length=30)
    points = IntegerField()

    # ── Anti-cascade flag ─────────────────────────────────
    # DIRECT / COLLECTIF / CANCEL
    source_type = CharField(max_length=20)

    # ── Action type ───────────────────────────────────────
    # Malus / Bonus / Malus_Collectif / Annulation
    type_action = CharField(max_length=30)

    # ── Point snapshot ────────────────────────────────────
    points_avant = IntegerField()
    points_apres = IntegerField()
    zone_avant = CharField(max_length=20)
    zone_apres = CharField(max_length=20)

    # ── Metadata ──────────────────────────────────────────
    commentaire = TextField(null=True, default=None)
    annule = BooleanField(default=False)
    # Reference to the log that was cancelled (for SYS-CANCEL entries)
    ref_log_annule = ForeignKeyField(
        "self", backref="cancellations", null=True, default=None,
        on_delete="SET NULL",
    )

    # ── Timestamp ─────────────────────────────────────────
    timestamp = DateTimeField(default=datetime.now)

    class Meta:
        table_name = "log"

    def __repr__(self):
        return (
            f"<Log id={self.id} conscrit={self.conscrit_id} "
            f"code={self.code_infraction} pts={self.points} "
            f"src={self.source_type} annule={self.annule}>"
        )
